num_epoch: 1000
num_episodes: 10
num_episodes_baseline: 50
# num_episodes_baseline: 5
# lr: 0.01
lr: 0.0005
clip_value: 0.1
entropy_reg_strength: 0.2
# entropy_reg_strength: 0.05
risk_epsilon: 0.5

instance_path: "./examples/len1024taxa50"

reload_checkpoint_path: "./checkpoint/train_on_generateemprical_GTR+I+G_final.pt"


env:
  # batch_size: 4
  batch_size: 1
  # batch_size: 128
  # BATCH_SIZE: 8
  sequence_type: DNA_WITH_GAP

model:
  vocab_size: 4
  patch_size: 1
  # fixed_length: 1024
  embed_dim: 64
  num_enc_heads: 8
  num_enc_layers: 6