num_epoch: 1000
num_episodes: 10
num_episodes_baseline: 50
# num_episodes_baseline: 5
# lr: 0.01
lr: 0.001
clip_value: 0.1
entropy_reg_strength: 0.2
# entropy_reg_strength: 0.05
risk_epsilon: 0.5

# replay_buffer_size: 48
# replay_buffer_size: 16
# replay_buffer_size: 2
# replay_buffer_sample_size: 2
# replay_buffer_sample_size: 24

# replay_buffer_score_bound: 20

# summary_name: "G_l_1000_n_100_0.0_0.05_0__temp2.0"
# summary_name: "G_l_1024_n_20_0.0_0.04_0_train20_30_patch4_rbsample16_bs32"
# summary_path: "tb_opt_RL_finetune_dataTaxa20"
# summary_path: "NULL"
# summary_path: "tb_step_loss"
# checkpoint_path: "policy_checkpoints"



# instance_path: "/home/dingshizhe/mnt/iclr_2024_phylogfn_suppl/PGPI/data_gen/CSolver/raxml/fixed_len_data/len512/taxa30"
# sequences_file: "G_l_512_n_30_0.0_0.08_0.phy"
# raw_tree_file: ""
# c_best_tree_file: "G_l_512_n_30_0.0_0.08_0.tre"


# instance_path: "/home/dingshizhe/mnt/iclr_2024_phylogfn_suppl/PGPI/data_gen/fixed_len_data/len256/taxa30"
# sequences_file: "G_l_256_n_30_0.0_0.07_0.phy"
# raw_tree_file: ""
# c_best_tree_file: "G_l_256_n_30_0.0_0.07_0.tre"


# instance_path: "/home/dingshizhe/mnt/iclr_2024_phylogfn_suppl/PGPI/data_gen/CSolver/raxml/fixed_len_data_test/len256/taxa100"
instance_path: "/home/dingshizhe/PhyloNet_bak/data_gen/CSolver/raxml/fixed_len_data_test/len256/taxa100"
# sequences_file: "G_l_1024_n_20_0.0_0.04_0.phy"
# raw_tree_file: "G_l_1024_n_20_0.0_0.04_0_raw.tre"
# c_best_tree_file: "G_l_1024_n_20_0.0_0.04_0.tre"

reload_checkpoint_path: "/home/dingshizhe/NeuralNJ/checkpoint/checkpoint_100.pt"



env:
  # batch_size: 4
  batch_size: 21
  # batch_size: 128
  # BATCH_SIZE: 8
  sequence_type: DNA_WITH_GAP

model:
  vocab_size: 4
  patch_size: 2
  fixed_length: 1024
  embed_dim: 32
  encoder_attn_layers: 2
  num_enc_heads: 2